---
title: "Flight summaries"
author: "Matt"
subtitle: "`r paste0('updated: ',format(Sys.time(), '%d/%m/%y'))`"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(qwraps2_markup = "markdown")
library(tidyverse)
library(readr)
library(qwraps2)
library(Kulan)
library(ggpubr)
```



```{r make a large dataset, echo=FALSE, message=FALSE, warning=FALSE}
path="data/tables"
all_dfs=Kulan::get_tables(path)
```


```{r load the data, echo=FALSE, message=FALSE, warning=FALSE}
# Load RDS ----------------------------------------------------------------


All_Flight_Right <- readRDS("C:/Users/matthew.grainger/Documents/Projects_in_development/Kulan/data/All_Flight_Right.RDS")


```

```{r apply grd_in_img function, echo=FALSE, message=FALSE, warning=FALSE}
# For all flights AND each flight  ----------------------------------------

## Get mean & range of ground in image -------------------------------------

data<-All_Flight_Right %>%
  rowwise() %>%
  mutate("grd_in_img"=grd_in_img(`Alt above ground`)) %>%
  janitor::clean_names() # Tidy the column names to make it easier to plot

```

```{r Remove odd data, echo=FALSE, message=FALSE, warning=FALSE}
# Remove empty photographs ------------------------------------------------

#dim(data)[1]
oddname<-data %>% 
   filter(str_detect(photo_no, "IMG"))
#dim(oddname)[1]# 20 empty phots

data<-data %>% 
  filter(!str_detect(photo_no, "IMG")) # remove the odd photos from the data

#dim(data)

#names(data)
```

## Strip-width summary

```{r, results='asis', echo=FALSE,, message=FALSE, warning=FALSE}
# data %>% 
#   group_by(id) %>%
#   select(grd_in_img) %>% 
#   summarise(mn=mean(grd_in_img), sd=sd(grd_in_img), min=min(grd_in_img), max=max(grd_in_img))


our_summary1 <-
  list("strip width" =
         list("min"       = ~ round(min(grd_in_img)),
              "max"       = ~ round(max(grd_in_img)),
              "mean (sd)" = ~ qwraps2::mean_sd(grd_in_img)))


tab_1<-qwraps2::summary_table(dplyr::group_by(data, id),our_summary1)
tab_1

```


## Altitude summary

### Altitude above ground

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(alt_above_ground, id)%>% 
  ggplot(aes(x=alt_above_ground,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Altitude above ground", y="Frequency")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,300, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45,size=8))
 


```

### Altitude above sea level

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(alt_above_the_sea_level, id)%>% 
  ggplot(aes(x=alt_above_the_sea_level,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Altitude above sea level", y="Frequency")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,300, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45,size=8))
 


```

### Altitude above launch site

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(alt_above_launch_point, id)%>% 
  ggplot(aes(x=alt_above_launch_point,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Altitude above lauch point", y="Frequency")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,300, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(angle = 45,size=8))
 


```

## Speed summary

### Speed

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(speed, id)%>% 
  ggplot(aes(x=speed,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Speed")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,120, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")#+
  #theme(axis.text.x = element_text(angle = 45,size=8))
 

```

### GPS speed

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_speed, id)%>% 
  ggplot(aes(x=gps_speed,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="gps speed")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,160, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  theme(axis.text.x = element_text(size=8))
 

```

## Roll and pitch summary 

### Banking angle

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# data %>% 
#   select(banking_angle, id)%>% 
#   ggplot(aes(x=banking_angle,fill=id)) +
#   geom_histogram(binwidth = 1, boundary=-40)+
#   coord_polar()+
#   scale_x_continuous(limits = c(-40,40))+
#   facet_wrap(~id)+
#   Kulan::theme_dark_blue()+
#   theme(legend.position = "none")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}

data %>% 
  select(banking_angle, id)%>% 
  ggplot(aes(x=banking_angle,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Banking angle")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(-30,30, by=10))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")#+
  #theme(axis.text.x = element_text(angle = 45,size=8))
 

```


### Pitch 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(tangage, id)%>% 
  ggplot(aes(x=tangage,fill=id)) +
  geom_dotplot()+
  #geom_histogram(bins=30)+
  labs(x="Pitch (Tangage)")+
  facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(-10,30, by=10))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")#+
  #theme(axis.text.x = element_text(angle = 45,size=8))
 

```

## Azimuth

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==1) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 1")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==2) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 2")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==3) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 3")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==4) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 4")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==5) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 5")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==6) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 6")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==7) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 7")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(azimuth, id)%>% 
  filter(id==8) %>% 
  ggplot(aes(x=azimuth,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Azimuth")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("Azimuth for Flight 8")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))
 

```

### GPS Course

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==1) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 1")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==2) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 2")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==3) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 3")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==4) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 4")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==5) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 5")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==6) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 6")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==7) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 7")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(gps_course, id)%>% 
  filter(id==8) %>% 
  ggplot(aes(x=gps_course,fill=id)) +
  geom_bar(width=1)+
  coord_polar()+
  labs(x="Course")+
 # facet_wrap(id~.)+
   scale_y_continuous(NULL, breaks = NULL)+
  scale_x_continuous(breaks=seq(0,360, by=20))+
  Kulan::theme_dark_blue()+
 #theme_Publication()+
  theme(legend.position = "none")+
  ggtitle("GPS course for Flight 8")
#+
 # theme(axis.text.x = element_text(angle = 45,size=8))

```


## Date 

```{r date, echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  select(date, id) %>% 
  ggplot(aes(date, fill=id))+
  geom_bar()+
  #geom_text(aes(label=id), position=position_dodge(width=0.9), vjust=-0.25)+
  Kulan::theme_dark_blue()
  
  
```

```{r time, echo=FALSE, message=FALSE, warning=FALSE}
 data %>% 
  select(time, id) %>%
  rowid_to_column() %>% 
  ggplot(aes(time, rowid, fill=id))+
  geom_line(width=3, colour="blue")+
  scale_y_continuous(NULL, breaks = NULL)+
  facet_wrap(id~.)+
   Kulan::theme_dark_blue()+
  theme(axis.text.x = element_text(angle = 45,size=8,hjust = 1))
#   
```

# Ground sample distance (straight down)


```{r}
data<-data %>%
  rowwise() %>%
  mutate("gsd"=get_GSD(Altitude = alt_above_ground))

#cm/px

plot_data<-data %>% 
  select(id,gsd)
plot_data %>% 
  group_by(id) %>% 
  summarise(mean=mean(gsd, na.rm = TRUE), sd=sd(gsd, na.rm = TRUE))

```

